include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_return_types_on_setters
    - camel_case_types
    - constant_identifier_names
    - empty_catches
    - library_names
    - non_constant_identifier_names
    - prefer_final_fields
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_const
    - unnecessary_new